#pragma once

// #define SPLIT_HAND_PIN GP0
#define MASTER_LEFT

// #define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP20
// #define SERIAL_USART_RX_PIN GP21

#define I2C_DRIVER I2CD0
#define OLED_UPDATE_INTERVAL 50
#define I2C1_SDA_PIN GP16
#define I2C1_SCL_PIN GP17


// #define AUDIO_PIN GP22
// #define AUDIO_PWM_DRIVER PWMD3
// #define AUDIO_PWM_CHANNEL RP2040_PWM_CHANNEL_A

#define PMW33XX_CS_PIN GP13
#define SPI_DRIVER SPID1
#define SPI_SCK_PIN GP14
#define SPI_MISO_PIN GP12
#define SPI_MOSI_PIN GP15

// #define PMW33XX_CS_PIN_RIGHT GP13
// #define PMW33XX_LIFTOFF_DISTANCE 0x04

#define SPLIT_MAX_CONNECTION_ERRORS 10
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_LEFT
#define POINTING_DEVICE_DEBUG
// #define POINTING_DEVICE_RIGHT

// #define MUSIC_MAP
