#pragma once

#define MASTER_LEFT

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 200U
#define PICO_XOSC_STARTUP_DELAY_MULTIPLIER 64


#define PMW33XX_CS_PIN GP25

// #define PMW33XX_LIFTOFF_DISTANCE 0x04
// #define SPI_SCK_PIN GP26
// #define SPI_MISO_PIN GP24
// #define SPI_MOSI_PIN GP27
